     import mysql.connector

    mydb = mysql.connector.connect(host='localhost',
                                   user='root',
                                   passwd='1234', 
                                   database='classicmodels')

    # drop table count 

    mycursor = mydb.cursor()
    mycursor.execute("DROP TABLE IF EXISTS Counts")

    # Create a table named "customers":

    mycursor = mydb.cursor()
    mycursor.execute("CREATE TABLE Counts (org TEXT, count VARCHAR(255))")

    fname = "mbox.txt"

    with open(fname, "r") as f:
        fh = f.readlines()

    for line in fh:

        if not line.startswith('From: ') :
            continue
        pieces = line.split()
        email = pieces[1]
        parts = email.split("@")
        org = parts[-1]


        # -------------------------------
        mycursor = mydb.cursor()
        mycursor.execute('SELECT count FROM Counts WHERE org = %s', (org, ))
        myresult = mycursor.fetchone()
        #----------------------------------

        if myresult is None:
            print("[INFO] No Records Found..")

            mycursor = mydb.cursor()
            mycursor.execute('INSERT INTO Counts (org, count)  VALUES ( %s, 1 )', ( org, ) )

            mydb.commit()

            print("[INFO] ", mycursor.rowcount, "record inserted...")

        else:
            mycursor = mydb.cursor()
            mycursor.execute('UPDATE Counts SET count=count+1 WHERE org = %s',(org, ))
            mydb.commit()

            print("[INFO] ", mycursor.rowcount, "record Updated...")




    sqlstr = 'SELECT org, count FROM Counts ORDER BY count DESC'

    mycursor = mydb.cursor()
    mycursor.execute(sqlstr)
    myresult = mycursor.fetchall()
    print()
    print("Final Output-----------------------------------")
    for x in myresult:
        print(x)

    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...
    [INFO]  1 record Updated...

    Final Output-----------------------------------
    ('caret.cam.ac.uk', '3')
    ('gmail.com', '3')
    ('iupui.edu', '24')
    ('umich.edu', '21')
    ('uct.ac.za', '19')
    ('media.berkeley.edu', '12')

    pwd

    'W:\\akshay-Python-Programming\\1. Basic Python Programming\\SQL_ASSIGNMENT'